/* NAV */
import { api, auth, requireAuth } from './api.js';
import { el, qs, icon, esc } from './ui.js';

const NAV = [
  { group: 'Overview', items: [{ path: '/', label: 'Dashboard', icon: 'dashboard' }, { path: '/analytics', label: 'Analytics', icon: 'chart' }] },
  { group: 'Catalogue', items: [{ path: '/products', label: 'Products', icon: 'box' }, { path: '/categories', label: 'Categories', icon: 'tag' }, { path: '/inventory', label: 'Inventory', icon: 'layers', badge: 'lowStock' }] },
  { group: 'Operations', items: [
    { path: '/bookings', label: 'Service Bookings', icon: 'calendar', badge: 'pending' }, { path: '/calendar', label: 'Calendar', icon: 'clock' }, { path: '/dispatch', label: 'Dispatch Board', icon: 'truck' }, { path: '/services', label: 'Services', icon: 'wrench' }, { path: '/equipment', label: 'Equipment', icon: 'settings' }, { path: '/service-history', label: 'Service History', icon: 'history' }, { path: '/estimates', label: 'Estimates', icon: 'file' }, { path: '/invoices', label: 'Invoices', icon: 'file' }, { path: '/orders', label: 'Orders', icon: 'file' }
  ] },
  { group: 'People', items: [{ path: '/customers', label: 'Customers', icon: 'users' }, { path: '/messages', label: 'Messages', icon: 'mail', badge: 'unread' }] },
  { group: 'Supplier Marketplace', items: [{ path: '/supplier-marketplace', label: 'Marketplace Dashboard', icon: 'dashboard' }, { path: '/suppliers', label: 'Suppliers', icon: 'warehouse' }, { path: '/supplier-integrations', label: 'Integrations / Plugins', icon: 'plug' }, { path: '/supplier-imports', label: 'Import Products', icon: 'upload' }, { path: '/supplier-products', label: 'Supplier Products', icon: 'box' }, { path: '/supplier-fulfillment', label: 'Fulfillment', icon: 'truck' }, { path: '/supplier-shipping', label: 'Shipping', icon: 'globe' }, { path: '/supplier-sync', label: 'Sync & Automation', icon: 'refresh' }, { path: '/supplier-logs', label: 'Sync Logs', icon: 'history' }, { path: '/supplier-settings', label: 'Marketplace Settings', icon: 'settings' }] },
  { group: 'Administration', items: [{ path: '/settings', label: 'Settings', icon: 'settings' }, { path: '/users', label: 'Team', icon: 'user', adminOnly: true }, { path: '/audit', label: 'Audit Log', icon: 'shield', adminOnly: true }] },
  { group: 'Website', items: [{ path: '/content', label: 'Website Content', icon: 'edit' }, { path: '/media', label: 'Media Library', icon: 'image' }] }
];

function navMarkup(user) { return NAV.map((group, gi) => { const items = group.items.filter(i => !i.adminOnly || user?.role === 'ADMIN'); const groupId = `nav-group-${gi}`; return `<section class="nav-group"><button type="button" class="nav-group__toggle" aria-expanded="false" aria-controls="${groupId}"><span class="nav-group__label">${esc(group.group)}</span><span class="nav-group__chevron" aria-hidden="true">⌄</span></button><div class="nav-group__items" id="${groupId}" hidden>${items.map(i => `<a class="nav-link" href="#${i.path}" data-path="${i.path}">${icon(i.icon)}<span>${esc(i.label)}</span>${i.badge ? `<span class="nav-link__badge" data-badge="${i.badge}" hidden>0</span>` : ''}</a>`).join('')}</div></section>`; }).join(''); }

export async function renderShell(user) { document.body.innerHTML = `<aside class="sidebar" id="sidebar" aria-label="Main navigation"><div class="sidebar__brand"><strong>N&D'S Admin</strong><span>HVAC · Refrigeration</span></div><nav class="sidebar__nav">${navMarkup(user)}</nav></aside><main id="view"></main>`; document.querySelectorAll('.nav-group__toggle').forEach(toggle => toggle.addEventListener('click', () => { const items = toggle.nextElementSibling; const expanded = toggle.getAttribute('aria-expanded') === 'true'; toggle.setAttribute('aria-expanded', String(!expanded)); items.hidden = expanded; })); }

const routes = { '/': () => import('./pages/dashboard.js'), '/analytics': () => import('./pages/analytics.js'), '/products': () => import('./pages/products.js'), '/categories': () => import('./pages/categories.js'), '/inventory': () => import('./pages/inventory.js'), '/bookings': () => import('./pages/bookings.js'), '/calendar': () => import('./pages/calendar.js'), '/dispatch': () => import('./pages/dispatch.js'), '/services': () => import('./pages/services.js'), '/equipment': () => import('./pages/equipment.js'), '/service-history': () => import('./pages/service-history.js'), '/estimates': () => import('./pages/estimates.js'), '/invoices': () => import('./pages/invoices.js'), '/orders': () => import('./pages/orders.js'), '/customers': () => import('./pages/customers.js'), '/messages': () => import('./pages/messages.js'), '/settings': () => import('./pages/settings.js'), '/users': () => import('./pages/users.js'), '/audit': () => import('./pages/audit.js'), '/profile': () => import('./pages/profile.js'), '/content': () => import('./pages/content.js'), '/media': () => import('./pages/media.js'), '/supplier-marketplace': () => import('./pages/supplier-marketplace.js'), '/suppliers': () => import('./pages/suppliers.js'), '/supplier-integrations': () => import('./pages/supplier-integrations.js'), '/supplier-imports': () => import('./pages/supplier-imports.js'), '/supplier-products': () => import('./pages/supplier-products.js'), '/supplier-fulfillment': () => import('./pages/supplier-fulfillment.js'), '/supplier-shipping': () => import('./pages/supplier-shipping.js'), '/supplier-sync': () => import('./pages/supplier-sync.js'), '/supplier-logs': () => import('./pages/supplier-logs.js'), '/supplier-settings': () => import('./pages/supplier-settings.js') };

export function setTitle(title) { document.title = `${title} · N&D'S Admin`; }
export function highlightNav(path) { document.querySelectorAll('.nav-group').forEach(group => { const active = group.querySelector(`.nav-link[data-path="${path}"]`); const toggle = group.querySelector('.nav-group__toggle'); const items = group.querySelector('.nav-group__items'); if (active) { document.querySelectorAll('.nav-link.active').forEach(x => x.classList.remove('active')); active.classList.add('active'); toggle.setAttribute('aria-expanded','true'); items.hidden = false; } }); }
export { routes, navMarkup };
