const prisma = require('../lib/prisma');
const { verifyAccessToken } = require('../lib/tokens');
const { ACCESS_COOKIE } = require('../lib/cookies');
const { unauthorized, forbidden } = require('../lib/errors');
const { DEFAULT_TENANT } = require('../lib/tenant');
const { roleFor, hasPermission } = require('../lib/permissions');
function extractToken(req) { const header = req.headers.authorization; if (header && header.startsWith('Bearer ')) return header.slice(7).trim(); return req.cookies?.[ACCESS_COOKIE] || null; }
async function protect(req, res, next) { try { const token = extractToken(req); if (!token) throw unauthorized('Authentication required'); let payload; try { payload = verifyAccessToken(token); } catch (e) { throw unauthorized(e.name === 'TokenExpiredError' ? 'Access token expired' : 'Invalid token'); } const user = await prisma.user.findUnique({ where: { id: payload.sub }, select: { id: true, name: true, email: true, role: true, isActive: true, avatarUrl: true, phone: true, businessId: true } }); if (!user || !user.isActive) throw unauthorized('Account not found or disabled'); req.user = user; req.role = roleFor(user); req.tenantId = user.businessId || DEFAULT_TENANT; if (user.businessId) { const business = await prisma.business.findUnique({ where: { id: user.businessId }, select: { status: true } }); if (!business || business.status !== 'ACTIVE') throw forbidden('This business account is suspended'); } next(); } catch (err) { next(err); } }
const authorize = (...roles) => (req, res, next) => { if (!req.user) return next(unauthorized('Authentication required')); const semanticRole = roleFor(req.user); if (!roles.includes(req.user.role) && !roles.includes(semanticRole)) return next(forbidden('Insufficient role for this action')); next(); };
const requirePermission = (permission) => (req, res, next) => { if (!req.user) return next(unauthorized('Authentication required')); if (!hasPermission(req.user, permission)) return next(forbidden('Insufficient permission for this action')); next(); };
const adminOnly = authorize('ADMIN');
async function optionalAuth(req, res, next) { const token = extractToken(req); if (!token) return next(); try { const payload = verifyAccessToken(token); req.user = await prisma.user.findUnique({ where: { id: payload.sub }, select: { id: true, name: true, email: true, role: true, isActive: true, businessId: true } }) || undefined; if (req.user) req.role = roleFor(req.user); if (req.user?.businessId) req.tenantId = req.user.businessId; } catch (_) {} next(); }
module.exports = { protect, authorize, requirePermission, adminOnly, optionalAuth, extractToken };
